#ENC[AES256_GCM,data:NoFyPeJHtBX9ooxsPvOS35bRcOh6gW3KhX3xnY/D9tRaTnk8LVU=,iv:hQFZVgyI59OBUXlPELHtVItwVG5O8IyW6l16s3nVfYc=,tag:Fga4vuLCWB+lybAGU6K2Bg==,type:comment]
#
#ENC[AES256_GCM,data:YYHdV80oT722P+ZkT03KCmxmlfj/xjFP5HZrb4X9JFmRpXm4DgQXYytCriBN9FC4bVpOHQPczG3ToE4S6jHSWaYJczM=,iv:3xVtT562IvmydK0sX4ztf0EExGjXXVtHoALr28Wg3Kw=,tag:vDWEYQfxrLWTokzGt09tHQ==,type:comment]
#ENC[AES256_GCM,data:d4aICUTohP2O4rXH86aShwcobK5TLyWxkSKLcqBfTFE47XCg3w==,iv:XWAjpXrdcULAElfZOM296X9cFGvD8TK8sVD+vc4vcmg=,tag:JhiW+fMol6E8wRWJAB37qQ==,type:comment]
#
#ENC[AES256_GCM,data:fCYv58vYAI8mEr7IhHBR+PmNylRrfSvO4gPu9ZZFGZ2x0KlJrSRHr8kUPHKpHMBhckc68kz43igXY2S8j0hlTGY4+W6BPQwoF6YZRAuJAyFB+TadPP1ZFysbjxGBWfWIzYKk,iv:PoIB467SwgvZ2Q8lgOLYzsnQIcXoY8opRozWCRJY9Y8=,tag:msK4tJmVie1XvtnQx8LCCA==,type:comment]
#ENC[AES256_GCM,data:NL4dGxQYk7NfFZB1oowXLNHVbUSgF5ERQq4/ZF/iObQOgUcAnLsMdK7NX+kbcQq7hunTrBc=,iv:+L9MH9U7Y9lV8OoMQ4LfejCLzWNCzXXNLGERM7pbmf8=,tag:h+MfzPiDqmLcANWi+MPzeQ==,type:comment]
#
#ENC[AES256_GCM,data:N4xXjwtRH9qhVFWjHN5qUpbP8By2AyT8BXNfSok40U4PBscvVa44uVKL5oXgEiuDz1oUa/8Zb59ZOKExjLO6eBOm,iv:s4ePggzqVVXaG9ovmvP/vp7rzsyHnY+ICUE12lfFCGE=,tag:G1b5R4NJRU0i+8+gkY5w1g==,type:comment]
postgresql:
    auth:
        password: ENC[AES256_GCM,data:OqJD7BY3gWiGRNkVbP8/,iv:x4OCP4tNzZNwmHyH6+NplZwBUOMtD8qwlzBuxM1Ty/w=,tag:AyVRAtqAt52TJCdWGX0W7g==,type:str]
        postgresPassword: ENC[AES256_GCM,data:NQ/WW3NgE2q91grhzWrNXm4=,iv:YNAgA9kjB4TfkqYia7vcc0PYnhqLf1dx6Zm7I0ejzAU=,tag:iGJEFvB+3L6SAFXIeL0Xeg==,type:str]
sops:
    age:
        - recipient: age1uz9zgllclydqddp8u0l7f3vjtg2ak5htt7hsuqwgyp2myjytgvfqgwgapn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY0xXbWtDR2JXOG5BWGJ4
            SVpkTE1iOE8zMGJpYWtROXVCL3A3S0xOaDNjCkVPM1VpYjQ2a0ZtK0dDNU14Qm5t
            Y1FTc1pOS1hsYkhaL0twVmYrcjI2bUEKLS0tIG5qa242M2VpOTdIc21hU2E3M3I3
            WDAwR0dWcnpscDRwQ21hMGNIS1JTNE0KdKV89HVMin/WkHVhr4VZP1dd1IhwI4wl
            OiUJrFGNvwRYeBU4GHNXvrEYm+j1j9obFUAyPFJN/zo39XA/tVtGJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T11:41:35Z"
    mac: ENC[AES256_GCM,data:OPDFBwLga2WbR9uELDtUsLTqaC3Yb9cei3r3ygm3Nx8wZ1lvTx95gNKQTFVJhDZaxjveCcCP3R7kW8cLwjMp/868/UtO1ZTqD0IbZW4MrDjCPySqzY83wQ5i/mqp1vwyYQfryD2+AIuF84PYMz2QgHTDc6nGm3jbgmogVnUAhdc=,iv:RXDue/E0lFiicUXIfrDAFT+DuXkm7+CBVKUKCmykE9M=,tag:9hUJRVJ1a1f5/TWtNvSrLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
